### ISSUE TITLE
Fix 'Unnecessary semicolon.' issue in modules\2-factor-auth.js

### ISSUE THREAD

**Issue by AfterNetwork** [AfterNetwork-SmileyCreations-Projects/Smile.js#12]
[CodeFactor](https://www.codefactor.io/repository/github/afternetwork-smileycreations-projects/smile.js) found an issue: Unnecessary semicolon.

It's currently on:
[modules\2-factor-auth.js:14
](https://www.codefactor.io/repository/github/afternetwork-smileycreations-projects/smile.js/source/develop/modules/2-factor-auth.js#L14)Commit 65fd2250f7b8ee166e66a9709325cea2b4042117

**Comment by smileycreations15** [comment]
Fixed
