### ISSUE TITLE
CircleCI - Problem with config.yml

### ISSUE THREAD

**Issue by AfterNetwork** [AfterNetwork-smileycreations-Projects/Smile.js#19]

**Comment by smileycreations15** [comment]
@AfterNetwork I am currently fixing it.

**Comment by smileycreations15** [comment]
@AfterNetwork Also we have a new app.

**Comment by AfterNetwork** [comment]
* In step 2 definition: Invalid step structure (expected string or map, got config.StepDescription)

**Comment by smileycreations15** [comment]
@AfterNetwork Fixing it. Also there is a new pull request bot.

**Comment by smileycreations15** [comment]
@AfterNetwork fixed
