### ISSUE TITLE
PLEASE NOTE: BRANCH RULES

### ISSUE THREAD

**Issue by AfterNetwork** [AfterNetwork-smileycreations-Projects/Smile.js#2]
Please only add your files in the "develop" branch now, it will be merged time from time.
DO NOT MERGE DEVELOP WITH MASTER WITHOUT MY PERMISSION OR ELSE

**Comment by MCloverz** [comment]
YES SIR!

**Comment by smileycreations15** [comment]
> Please only add your files in the "develop" branch now, it will be merged time from time.
> DO NOT MERGE DEVELOP WITH MASTER WITHOUT MY PERMISSION OR ELSE

PROTECT DA BRANCH!

**Comment by smileycreations15** [comment]
@AfterNetwork The branch is write-protected. You need to create a pıull request and wait for other 2 users to approve

**Comment by smileycreations15** [comment]
This means you cannot merge without me and mcloverz approving it.

**Comment by smileycreations15** [comment]
cc @the-afternetwork-projects/programming-team

**Comment by AfterNetwork** [comment]
> This means you cannot merge without me and mcloverz approving it.
I have admin power, so I can override that rule.

**Comment by AfterNetwork** [comment]
oops

**Comment by smileycreations15** [comment]
@AfterNetwork me too

**Comment by AfterNetwork** [comment]
> @AfterNetwork me too

I can demote you

**Comment by smileycreations15** [comment]
@AfterNetwork I will never override lol. Should we enforce administrators?

**Comment by smileycreations15** [comment]
@AfterNetwork Please promote me, I will never override.

**Comment by smileycreations15** [comment]
@AfterNetwork did you read my messages?

**Comment by AfterNetwork** [comment]
> @AfterNetwork did you read my messages?

Sorry, I was doing some biology course, anyways no. I like it that way.
