### ISSUE TITLE
Setting up GreenKeeper

### ISSUE THREAD

**Issue by AfterNetwork** [AfterNetwork-smileycreations-Projects/Smile.js#26]
https://account.greenkeeper.io/account/AfterNetwork-smileycreations-Projects

**Comment by AfterNetwork** [comment]
Special info:

- https://greenkeeper.io/docs.html#prerequisites

**Comment by AfterNetwork** [comment]
cc @smileycreations15

**Comment by smileycreations15** [comment]
@AfterNetwork I could not set it up.

**Comment by AfterNetwork** [comment]
Whatever, just login into our organization at greenkeeper.io

**Comment by smileycreations15** [comment]
> Whatever, just login into our organization at greenkeeper.io

@AfterNetwork The issue: We don't have a package.json and we don't have any dependencies.

**Comment by smileycreations15** [comment]
@AfterNetwork Can you also read the messages at @AfterNetwork-smileycreations-Projects/programming-team?
