### ISSUE TITLE
stale test

### ISSUE THREAD

**Issue by AfterNetwork** [AfterNetwork-smileycreations-Projects/Smile.js#35]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by smileycreations15** [comment]
@AfterNetwork There is no command like that, lol. 🤣

**Comment by smileycreations15** [comment]
> /polls 'Option1' 'Option 2' 'Option 3'

@AfterNetwork THERE IS NO COMMAND LIKE THAT! _screams_

**Comment by smileycreations15** [comment]
> /polls yes no maybe

@AfterNetwork There is no /polls command.
