### ISSUE TITLE
I LIKE TO CLOSE CLOSE IT CLOSE IT

### ISSUE THREAD

**Issue by AfterNetwork** [AfterNetwork-smileycreations-Projects/Smile.js#37]
DO YOU LIKE TO CLOSE IT CLOSE IT?
[![](https://api.gh-polls.com/poll/01DDPBE3P98HKVRMVR0RRPPW5P/Yes)](https://api.gh-polls.com/poll/01DDPBE3P98HKVRMVR0RRPPW5P/Yes/vote)
[![](https://api.gh-polls.com/poll/01DDPBE3P98HKVRMVR0RRPPW5P/No)](https://api.gh-polls.com/poll/01DDPBE3P98HKVRMVR0RRPPW5P/No/vote)
[![](https://api.gh-polls.com/poll/01DDPBE3P98HKVRMVR0RRPPW5P/Maybe)](https://api.gh-polls.com/poll/01DDPBE3P98HKVRMVR0RRPPW5P/Maybe/vote)

**Comment by smileycreations15** [comment]
I LIKE TO CLOSE IT...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................issue closed
