### ISSUE TITLE
THE BUILD IS FAILING

### ISSUE THREAD

**Issue by AfterNetwork** [AfterNetwork-smileycreations-Projects/Smile.js#61]

**Comment by smileycreations15** [comment]
no more

**Comment by AfterNetwork** [comment]
set. it. up.
https://codecov.io/gh/AfterNetwork-smileycreations-Projects/Smile.js

**Comment by smileycreations15** [comment]
h. o. w.?

**Comment by AfterNetwork** [comment]
https://codecov.io/gh/AfterNetwork-smileycreations-Projects/Smile.js/settings

**Comment by smileycreations15** [comment]
sorry i cannot do that i need to sleep
