### ISSUE TITLE
Redesign the ripple

### ISSUE THREAD

**Issue by AfterNetwork** [AfterNetwork-smileycreations-Projects/Smile.js#68]

**Comment by smileycreations15** [comment]
colors of ripple? You can set it by 
```js
smilejs.paper.rippleColor = "rgba(r,g,b,a)"
```

**Comment by AfterNetwork** [comment]
Nope, the code that makes the ripple.

**Comment by smileycreations15** [comment]
@AfterNetwork It is a perfect piece of code, ok?

**Comment by smileycreations15** [comment]
@AfterNetwork The code is perfect, it doesn't need changes

**Comment by AfterNetwork** [comment]
Put an example on smile.js’s website

**Comment by smileycreations15** [comment]
I'm doing it with the latest release.

**Comment by smileycreations15** [comment]
ripple is ok

**Comment by AfterNetwork** [comment]
Make it mobile friendly. It doesn’t work on my phone

**Comment by smileycreations15** [comment]
touchstart

**Comment by smileycreations15** [comment]
done with commit https://github.com/AfterNetwork-smileycreations-Projects/Smile.js/commit/1bea2da8b33352bef1f203f4b9691115a46b387b

**Comment by smileycreations15** [comment]
duh duh done with latest commit
