### ISSUE TITLE
Remake the blockchain

### ISSUE THREAD

**Issue by AfterNetwork** [AfterNetwork-smileycreations-Projects/Smile.js#69]
This will need to have evolved performance and quality, and make it perfect with making it long.
This is due by the 5th of September, due to this in v1.6.5. It's deadline for updates is on that date. THEN NO MERGING TO MASTER. Please work on this asignees or get a strike (7 Strikes and you are removed from the group)

**Comment by smileycreations15** [comment]
Please, don't remove me as I am also an owner. BLOCKCHAIN IS FINE AND IF ANY BUGS ARE FOUND THIS WILL BE REOPENED.

**Comment by smileycreations15** [comment]
blockchains are intended to be slow to prevent blocks from spamming the chain
