### ISSUE TITLE
Policy on External Links on AFSCP

### ISSUE THREAD

**Issue by AfterNetwork** [AfterNetwork-smileycreations-Projects/Smile.js#86]
AFSCP will be banning unapproved and third-party websites. This will go into effect on July 20th.
 
However, the following websites will be banned today and forever, and will be prevented from being linked to be kept on topic.

LIST OF WEBSITES BANNED:
chess.com

LIST OF WEBSITES _**TO BE**_ UNBANNED:
chess.com

LIST OF WEBSITES APPROVED:

*.smileycreations15.com (any subdomains)

Please note **NO** voting is allowed. This goes into effect ASAP. 

Chess.com will be an unapproved site due to it is causing distractions on work.
DEBATE:
```
@smileycreations15: CHESS.COM? NO WAY. WAT DA *BEEP*!!!???? WE ALL LOVE CHESS.
```

**Comment by smileycreations15** [comment]
I SAY NO FOR BANNING chess.com

**Comment by AfterNetwork** [comment]
It’s final. I am using my power to make this approved. No other admin will be able to talk here. No changing.

**Comment by smileycreations15** [comment]
not resolved

**Comment by AfterNetwork** [comment]
It is. Please do not link or demote

**Comment by smileycreations15** [comment]
move to internal

**Comment by smileycreations15** [comment]
https://github.com/orgs/AfterNetwork-smileycreations-Projects/teams/internal/discussions

**Comment by smileycreations15** [comment]
I didn't demote

**Comment by smileycreations15** [comment]
@AfterNetwork please gimme back owner ok chess.com is unapproved

**Comment by smileycreations15** [comment]
@AfterNetwork

**Comment by smileycreations15** [comment]
HEY

**Comment by smileycreations15** [comment]
@AfterNetwork please gimme back owner ok chess.com is unapproved

**Comment by AfterNetwork** [comment]
I will give you admin if you create live chess

**Comment by smileycreations15** [comment]
@AfterNetwork I created a chess implementation.

**Comment by smileycreations15** [comment]
@AfterNetwork Give back my admin

**Comment by smileycreations15** [comment]
@AfterNetwork We need a server for live chess, and that isn't available

**Comment by smileycreations15** [comment]
@AfterNetwork Do you own smileycreations? I own smileycreations. smileycreations merged with The AfterNetwork Projects and created this. I mostly created the code. You should give my owner access back. What would you think if I removed your owner access? You would probably think that you created a part of the project and would feel this is unfair. You would think it is abuse. I think the same.
